import React, { useState, useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import API from '../services/api';
import {
  Brain,
  Sparkles,
  ChevronLeft,
  ChevronRight,
  Star,
  CheckCircle,
  Loader2,
  Volume2
} from 'lucide-react';
import { useVoice } from '../hooks/useVoice';

const Flashcards = () => {
  const location = useLocation();
  const queryParams = new URLSearchParams(location.search);
  const urlNoteId = queryParams.get('noteId');

  const [notes, setNotes] = useState([]);
  const [selectedNoteId, setSelectedNoteId] = useState(urlNoteId || '');
  const [cards, setCards] = useState([]);
  const [loading, setLoading] = useState(false);
  const [notesLoading, setNotesLoading] = useState(true);

  // Carousel State
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  
  // Voice Hook
  const { speak, isSpeaking } = useVoice();

  const fetchNotes = async () => {
    try {
      setNotesLoading(true);
      const { data } = await API.get('/notes');
      setNotes(data);
      if (data.length > 0 && !selectedNoteId) {
        setSelectedNoteId(data[0]._id);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setNotesLoading(false);
    }
  };

  useEffect(() => {
    fetchNotes();
  }, []);

  // Fetch flashcards if noteId changes
  useEffect(() => {
    if (!selectedNoteId) return;

    const fetchCards = async () => {
      try {
        setLoading(true);
        setCards([]);
        setIsFlipped(false);
        setCurrentIndex(0);
        
        const { data } = await API.get(`/flashcards?subjectId=&isFavorite=&isLearned=&noteId=${selectedNoteId}`);
        setCards(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchCards();
  }, [selectedNoteId]);

  const handleGenerateCards = async () => {
    if (!selectedNoteId) return;

    try {
      setLoading(true);
      const { data } = await API.post('/flashcards', { noteId: selectedNoteId });
      setCards(data);
      setCurrentIndex(0);
      setIsFlipped(false);
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to generate flashcards');
    } finally {
      setLoading(false);
    }
  };

  const handleToggleLearned = async (id) => {
    try {
      const { data } = await API.patch(`/flashcards/${id}/learned`);
      setCards((prev) =>
        prev.map((c) => (c._id === id ? { ...c, isLearned: data.isLearned } : c))
      );
    } catch (err) {
      console.error(err);
    }
  };

  const handleToggleFavorite = async (id) => {
    try {
      const { data } = await API.patch(`/flashcards/${id}/favorite`);
      setCards((prev) =>
        prev.map((c) => (c._id === id ? { ...c, isFavorite: data.isFavorite } : c))
      );
    } catch (err) {
      console.error(err);
    }
  };

  const handleSpeakCard = (text, e) => {
    e.stopPropagation(); // Prevent card from flipping when clicking the speaker
    speak(text);
  };

  const handleNext = () => {
    if (currentIndex < cards.length - 1) {
      setIsFlipped(false);
      setTimeout(() => {
        setCurrentIndex((prev) => prev + 1);
      }, 150);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setIsFlipped(false);
      setTimeout(() => {
        setCurrentIndex((prev) => prev - 1);
      }, 150);
    }
  };

  return (
    <div className="space-y-6 pb-12">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold text-slate-800 dark:text-white">AI Flashcards</h2>
          <p className="text-slate-500 dark:text-slate-400 text-sm mt-0.5">
            Optimize concept recall with flipping memorization cards generated by AI
          </p>
        </div>

        {/* Note selector */}
        {!notesLoading && (
          <div className="flex items-center gap-3">
            <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Note:</span>
            <select
              value={selectedNoteId}
              onChange={(e) => setSelectedNoteId(e.target.value)}
              className="px-4 py-2.5 rounded-xl border border-slate-200 dark:border-darkBorder bg-white dark:bg-darkCard text-slate-700 dark:text-slate-300 focus:outline-none focus:ring-2 focus:ring-primary-500/20 text-xs font-semibold"
            >
              {notes.map((n) => (
                <option key={n._id} value={n._id}>
                  {n.title}
                </option>
              ))}
              {notes.length === 0 && <option value="">No notes uploaded</option>}
            </select>
          </div>
        )}
      </div>

      {loading ? (
        <div className="flex flex-col items-center justify-center min-h-[50vh] space-y-4">
          <Loader2 className="w-10 h-10 text-primary-600 animate-spin" />
          <p className="text-xs text-slate-500 font-semibold animate-pulse-slow">
            AI Assistant is conceptualizing key flashcards...
          </p>
        </div>
      ) : cards.length > 0 ? (
        <div className="max-w-xl mx-auto space-y-6">
          {/* Card Carousel Frame */}
          <div
            onClick={() => setIsFlipped(!isFlipped)}
            className="w-full h-80 cursor-pointer perspective-1000 group"
          >
            <div
              className={`w-full h-full relative transition-transform duration-500 transform-style-3d ${
                isFlipped ? 'rotate-y-180' : ''
              }`}
            >
              {/* CARD FRONT */}
              <div className="absolute inset-0 bg-white dark:bg-darkCard border border-slate-100 dark:border-darkBorder rounded-3xl shadow-md p-8 flex flex-col justify-between backface-hidden">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] uppercase font-bold text-slate-400">Card Front</span>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={(e) => handleSpeakCard(cards[currentIndex].front, e)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800"
                      title="Speak Front"
                    >
                      <Volume2 size={15} />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleToggleFavorite(cards[currentIndex]._id);
                      }}
                      className={`p-1.5 rounded-lg ${
                        cards[currentIndex].isFavorite ? 'text-amber-500' : 'text-slate-400'
                      }`}
                    >
                      <Star size={16} className={cards[currentIndex].isFavorite ? 'fill-amber-500' : ''} />
                    </button>
                  </div>
                </div>

                <div className="text-center my-auto px-4">
                  <p className="text-lg md:text-xl font-bold text-slate-800 dark:text-white leading-relaxed">
                    {cards[currentIndex].front}
                  </p>
                </div>

                <p className="text-center text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                  Click card to flip
                </p>
              </div>

              {/* CARD BACK */}
              <div className="absolute inset-0 bg-white dark:bg-darkCard border border-slate-100 dark:border-darkBorder rounded-3xl shadow-md p-8 flex flex-col justify-between rotate-y-180 backface-hidden">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] uppercase font-bold text-slate-400">Card Back</span>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={(e) => handleSpeakCard(cards[currentIndex].back, e)}
                      className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800"
                      title="Speak Back"
                    >
                      <Volume2 size={15} />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleToggleFavorite(cards[currentIndex]._id);
                      }}
                      className={`p-1.5 rounded-lg ${
                        cards[currentIndex].isFavorite ? 'text-amber-500' : 'text-slate-400'
                      }`}
                    >
                      <Star size={16} className={cards[currentIndex].isFavorite ? 'fill-amber-500' : ''} />
                    </button>
                  </div>
                </div>

                <div className="text-center my-auto px-4">
                  <p className="text-sm md:text-base font-semibold text-slate-700 dark:text-slate-200 leading-relaxed">
                    {cards[currentIndex].back}
                  </p>
                </div>

                <p className="text-center text-[10px] text-slate-400 font-bold uppercase tracking-wider">
                  Click card to flip
                </p>
              </div>
            </div>
          </div>

          {/* Control bar */}
          <div className="flex items-center justify-between px-4">
            <button
              onClick={handlePrev}
              disabled={currentIndex === 0}
              className="p-2 border border-slate-200 dark:border-darkBorder rounded-xl text-slate-500 disabled:opacity-40"
            >
              <ChevronLeft size={20} />
            </button>

            <div className="flex items-center gap-4">
              {/* Learned checkmark */}
              <button
                onClick={() => handleToggleLearned(cards[currentIndex]._id)}
                className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 border shadow-sm transition-all ${
                  cards[currentIndex].isLearned
                    ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20 text-emerald-600 dark:text-emerald-400'
                    : 'border-slate-200 dark:border-darkBorder text-slate-500 hover:bg-slate-50 dark:hover:bg-slate-800'
                }`}
              >
                <CheckCircle size={15} className={cards[currentIndex].isLearned ? 'fill-emerald-500 text-white dark:text-darkCard' : ''} />
                {cards[currentIndex].isLearned ? 'Learned' : 'Mark Learned'}
              </button>

              <span className="text-xs font-bold text-slate-400">
                {currentIndex + 1} / {cards.length}
              </span>
            </div>

            <button
              onClick={handleNext}
              disabled={currentIndex === cards.length - 1}
              className="p-2 border border-slate-200 dark:border-darkBorder rounded-xl text-slate-500 disabled:opacity-40"
            >
              <ChevronRight size={20} />
            </button>
          </div>
        </div>
      ) : (
        <div className="py-20 text-center bg-white dark:bg-darkCard border border-slate-100 dark:border-darkBorder rounded-3xl space-y-4 shadow-sm max-w-xl mx-auto">
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-primary-500 to-indigo-600 text-white flex items-center justify-center shadow-lg shadow-primary-500/10 mx-auto">
            <Brain size={26} />
          </div>
          <div>
            <h3 className="font-bold text-slate-800 dark:text-white">AI Flashcards Empty</h3>
            <p className="text-slate-500 dark:text-slate-400 text-xs mt-1.5 max-w-xs mx-auto">
              Analyze your notes document using AI to create smart revision flashcards.
            </p>
          </div>
          <button
            onClick={handleGenerateCards}
            disabled={!selectedNoteId}
            className="px-5 py-3 rounded-2xl bg-primary-600 hover:bg-primary-700 text-white font-semibold text-xs shadow-md transition-all disabled:opacity-50"
          >
            Generate Flashcards
          </button>
        </div>
      )}
    </div>
  );
};

export default Flashcards;
